version: '3.8'

services:
  websocket-server:
    build: .
    deploy:
      replicas: 3  # Run multiple instances of the WebSocket server
      restart_policy:
        condition: on-failure
    environment:
      - PORT=8080
    ports:
      - "8081-8083:8080"  # Exposing each replica on different local ports
    command: ["/bin/bash", "-c", "./start_servers.sh $PORT"]

  load-balancer:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - websocket-server
    command: ["/bin/bash", "-c", "./load_balancer.sh"]
